name: Clean up Preview Deployment
on:
  pull_request:
    types: [closed]

env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:

    - name: Delete Cloudflare Pages preview deployments
      run: |
        DEPLOY_BRANCH="preview/${{ github.event.pull_request.head.ref }}"
        deployment_ids=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ github.event.repository.name }}/deployments" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          | jq -r --arg DEPLOY_BRANCH "$DEPLOY_BRANCH" '.result[] | select(.deployment_trigger.metadata.branch == $DEPLOY_BRANCH) | .id')

        for deployment_id in $deployment_ids; do
          echo "Deleting deployment $deployment_id"
          curl -s -X DELETE "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/${{ github.event.repository.name }}/deployments/$deployment_id?force=true" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json"
        done
      
      # Delete Cloudflare Deployment
    - name: Delete Neon Branch
      uses: neondatabase/delete-branch-action@v3.1.3
      with:
        project_id: ${{ var.NEON_PROJECT_ID }}
        branch: preview/${{ github.event.pull_request.head.ref }}
        api_key: ${{ secrets.NEON_API_KEY }}